name: streaks
description: Sustainable Nutrition Management
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
  intl: ^0.17.0
  http: ^0.13.1
  shared_preferences: ^2.0.5
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  google_fonts: ^2.0.0
  flutter_spinkit: ^5.0.0
  cupertino_icons: ^1.0.2
  logger: ^1.0.0
  flutter_riverpod: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner:

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/